### ISSUE TITLE
Access csv files via DictWriter / DictReader only 

### ISSUE THREAD

**Issue by lucadealfaro** [ecoscape-earth/ecoscape-layers#12]
Don't do things like: 

```
            with open(map_codes_output_path, "r") as csvfile:
                reader = csv.reader(csvfile)
                next(reader)
                map_codes = [int(row[0]) for row in reader]
```

Open/close all csv files via DictReaders, and read/write to them using dictionaries, so that it's documented what fields you are using how.

**Comment by IanHollow** [comment]
This has now been changed to pandas for all csv file creation.
